# Generated by Django 4.2.2 on 2023-07-05 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('contact_number', models.CharField(max_length=10)),
                ('bio', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Not specified')], default='N', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('q1o1', models.ManyToManyField(blank=True, related_name='q1o1', to=settings.AUTH_USER_MODEL)),
                ('q1o2', models.ManyToManyField(blank=True, related_name='q1o2', to=settings.AUTH_USER_MODEL)),
                ('q1o3', models.ManyToManyField(blank=True, related_name='q1o3', to=settings.AUTH_USER_MODEL)),
                ('q2o1', models.ManyToManyField(blank=True, related_name='q2o1', to=settings.AUTH_USER_MODEL)),
                ('q2o2', models.ManyToManyField(blank=True, related_name='q2o2', to=settings.AUTH_USER_MODEL)),
                ('q2o3', models.ManyToManyField(blank=True, related_name='q2o3', to=settings.AUTH_USER_MODEL)),
                ('q3o1', models.ManyToManyField(blank=True, related_name='q3o1', to=settings.AUTH_USER_MODEL)),
                ('q3o2', models.ManyToManyField(blank=True, related_name='q3o2', to=settings.AUTH_USER_MODEL)),
                ('q3o3', models.ManyToManyField(blank=True, related_name='q3o3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', models.CharField(max_length=100)),
                ('from_user', models.CharField(max_length=100)),
                ('problem_solving', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4'), (5, 'Option 5')], max_length=255)),
                ('communication', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4'), (5, 'Option 5')], max_length=255)),
                ('sociability', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4'), (5, 'Option 5')], max_length=255)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('anonymous_from', models.CharField(max_length=100)),
                ('downvotes', models.ManyToManyField(blank=True, related_name='downvoted_reviews', to=settings.AUTH_USER_MODEL)),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvoted_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('to_user', 'from_user')},
            },
        ),
    ]
