# Generated by Django 4.2.2 on 2023-07-06 04:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='q4o1',
            field=models.ManyToManyField(blank=True, related_name='q4o1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='q4o2',
            field=models.ManyToManyField(blank=True, related_name='q4o2', to=settings.AUTH_USER_MODEL),
        ),
    ]
