# Generated by Django 4.2.1 on 2023-07-25 05:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='communication',
            new_name='Effective_Communication',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='problem_solving',
            new_name='Ethical_Professionalism',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='sociability',
            new_name='Responsible_Leadership',
        ),
        migrations.AddField(
            model_name='review',
            name='Thinking_and_Problem_Solving',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4'), (5, 'Option 5')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
