# Generated by Django 4.2.2 on 2023-06-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_rating',
            field=models.IntegerField(default=1),
        ),
    ]
