# Generated by Django 4.2.2 on 2023-07-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_poll_q4o1_poll_q4o2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='q4o1',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='q4o2',
        ),
    ]
