# Generated by Django 4.2.1 on 2023-07-25 12:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_review_effective_communication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Effective_Communication',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Team Player', 'Team Player'), ('Cooperative Collaborator', 'Cooperative Collaborator'), ('Supportive Teammate', 'Supportive Teammate'), ('Independent Worker', 'Independent Worker'), ('Relationship Builder', 'Relationship Builder'), ('Self-Reliant', 'Self-Reliant'), ('Friendly Service Provider', 'Friendly Service Provider'), ('Empathetic Listener', 'Empathetic Listener'), ('Culturally Neutral', 'Culturally Neutral'), ('Customer-Focused Problem-Solver', 'Customer-Focused Problem-Solver'), ('Approachable and Friendly', 'Approachable and Friendly'), ('Individual Contributor', 'Individual Contributor'), ('Empowering Coach', 'Empowering Coach'), ('Results-Focused Educator', 'Results-Focused Educator'), ('Effective Teacher', 'Effective Teacher')], max_length=255),
        ),
    ]
