# Generated by Django 4.2.1 on 2023-07-25 12:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_review_effective_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Ethical_Professionalism',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Reliable and Trustworthy', 'Reliable and Trustworthy'), ('Honest Communicator', 'Honest Communicator'), ('Sincere and Transparent', 'Sincere and Transparent'), ('Genuine and Authentic', 'Genuine and Authentic'), ('Respectful of Diversity', 'Respectful of Diversity'), ('Confident and Self-Assured', 'Confident and Self-Assured'), ('Hardworking and Dedicated', 'Hardworking and Dedicated'), ('Endurance', 'Endurance'), ('Detail-Oriented', 'Detail-Oriented'), ('Organized and Systematic', 'Organized and Systematic'), ('Ambitious and Aspiring', 'Ambitious and Aspiring'), ('Consistent but Moderate Performance', 'Consistent but Moderate Performance'), ('Patiently Ambitious', 'Patiently Ambitious'), ('Continuous Learner', 'Continuous Learner'), ('Pursuer of Excellence', 'Pursuer of Excellence')], max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='Responsible_Leadership',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Responsible Leader', 'Responsible Leader'), ('Responsible Delegator', 'Responsible Delegator'), ('Takes Ownership', 'Takes Ownership'), ('Engaging Team Manager', 'Engaging Team Manager'), ('People Person', 'People Person'), ('Inspirational Communicator', 'Inspirational Communicator'), ('Extraverted Networker', 'Extraverted Networker'), ('Visionary Thinker', 'Visionary Thinker'), ('Strategic Planner', 'Strategic Planner'), ('Future-Oriented', 'Future-Oriented'), ('Setting Realistic Goals', 'Setting Realistic Goals'), ('Self-Disciplined Professional', 'Self-Disciplined Professional'), ('Calm under Pressure', 'Calm under Pressure'), ('Self-Motivated', 'Self-Motivated'), ('Maintains Composure', 'Maintains Composure')], max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='Thinking_and_Problem_Solving',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Logical Problem Solver', 'Logical Problem Solver'), ('Systematic Decision Maker', 'Systematic Decision Maker'), ('Decisive Thinker', 'Decisive Thinker'), ('Cautious Evaluator', 'Cautious Evaluator'), ('Learning Oriented', 'Learning Oriented'), ('Quick Learner', 'Quick Learner'), ('Slow Learner', 'Slow Learner'), ('Sound Reasoner', 'Sound Reasoner'), ('Curious Explorer', 'Curious Explorer'), ('Outside-the-Box Thinker', 'Outside-the-Box Thinker'), ('Innovative and Original', 'Innovative and Original'), ('Careful and Reasoned', 'Careful and Reasoned'), ('Embraces Feedback', 'Embraces Feedback'), ('Accepts Constructive Criticism', 'Accepts Constructive Criticism'), ('Adaptable Team Player', 'Adaptable Team Player')], max_length=255),
        ),
    ]
