# Generated by Django 4.2.1 on 2023-06-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_rating',
        ),
        migrations.AddField(
            model_name='review',
            name='review_rating_1',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='review',
            name='review_rating_2',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='review',
            name='review_rating_3',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='review',
            name='review_rating_content_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='review_rating_content_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='review_rating_content_3',
            field=models.TextField(default=''),
        ),
    ]
