# Generated by Django 4.2.2 on 2023-07-26 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_review_effective_communication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='q1o4',
            field=models.ManyToManyField(blank=True, related_name='q1o4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='q2o4',
            field=models.ManyToManyField(blank=True, related_name='q2o4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='poll',
            name='q3o4',
            field=models.ManyToManyField(blank=True, related_name='q3o4', to=settings.AUTH_USER_MODEL),
        ),
    ]
