# Generated by Django 4.2.1 on 2023-06-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_review_review_remove_review_review_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_rating_content_1',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_rating_content_2',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_rating_content_3',
        ),
    ]
