# Generated by Django 4.2.1 on 2023-06-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_review_communication_review_problem_sol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='communication_bool',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='problem_bool',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sociability_bool',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='review',
            name='problem_sol',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='review',
            name='sociability',
            field=models.TextField(default='', max_length=400),
        ),
    ]
