# Generated by Django 4.2.1 on 2023-06-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_review_communication_bool_review_problem_bool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='communication_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='problem_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='sociability_bool',
            field=models.BooleanField(default=False),
        ),
    ]
