# Generated by Django 4.2.1 on 2023-07-05 16:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_review_review_rating_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='communication_bool',
        ),
        migrations.RemoveField(
            model_name='review',
            name='problem_solving_bool',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_rating_1',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_rating_2',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_rating_3',
        ),
        migrations.RemoveField(
            model_name='review',
            name='sociability_bool',
        ),
        migrations.AlterField(
            model_name='review',
            name='communication',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4'), (5, 'Option 5')], max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='problem_solving',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4'), (5, 'Option 5')], max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='sociability',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4'), (5, 'Option 5')], max_length=255),
        ),
    ]
